### ISSUE TITLE
Plotting Todo:

### ISSUE THREAD

**Issue by bencallaghan** [bencallaghan/sfari#1]
- [ ] Rewrite Plotting variants function in light of new organisation

- [ ] Plot 1: Variants / aaposition

- [ ] Plot 2: Variants plotted on gene diagram
